spec/openapi.json
Fixes a typo in the description of the `create notifications` operation. As docs are generated based on this spec, this fix will propagate to the API docs.
=> docs: fix typo

openapi/spec/openapi.json
Small fix, turns `phone_numbers` into a `string[]` instead of `unknown[]`.
=> fix: declare phone_numbers as being a string array

openapi/spec/openapi.json
Adds a missing field to `push-subscriptions-create` return type. It was present in the payload, but for some reason not mentioned in the response.
=> fix: add app_bundle_id to push-subscriptions-create return type

openapi/spec/openapi.json
Fixes the `notifications-list` response by adding missing fields like `archived_at`, `read_at`,  `seen_at` and `sent_at`, and replaces the `recipients` array with the `recipient` object, as a notification (delivery) only has a single recipient.
- [x ] Automated tests covering modified code pass
=> fix: add missing fields to notifications-list response

openapi/spec/openapi.json
Subscription endpoints had double entity wrappers in their response types (like `{ subscription: { subscription: { topic: … } } }`), and declared the `topic` param as being a query param instead of path param. This pull fixes the `subscription` resource.
=> fix: correct subscription response types and path params

docs/docs/index.mdx, docs/docs/react/known-issues.mdx, docs/sitemap.json, docs/src/components/menu/PageLink.tsx
Single commits can be reviewed independently:
- `to` in `PageLink` is now required
- External links in left nav are marked with an icon (see image below)
- Links to Slack replaced with links to GH Discussions (at the org level)
- Explain that Slack is for power users
---
=> GitHub discussions links

.github/actions/smoke-test/dist/index.js, openapi/scripts/smoke-test.ts, openapi/spec/openapi.json
- add error summary to smoke-test. If the test now errors, it will render a summary like the below, which makes tracing down the issues a bit easier:
```
---- Error Summary ----
✖ POST /notifications (id: notifications-create)
✖ HTTP 201: request with valid api key and payload returns expected response
error: {
"errors": [
{
"instancePath": "/notification",
"schemaPath": "#/properties/notification/additionalProperties",
"keyword": "additionalProperties",
"params": {
"additionalProperty": "sent_at"
},
"message": "must NOT have additional properties"
}
],
"data": {
"notification": {
"id": "33c05599-c764-4e48-a680-4ee5ef276ea2",
"title": "We're processing your order",
"content": "<p>Thank you for your order. We'll notify you when these items are ready.</p>",
"action_url": null,
"category": …
```
=> ci: add error summary to smoke-tests

docs/docs/sending-notifications.mdx, openapi/spec/openapi.json
The way it's phrased currently makes it seem that a notification can be sent to max 1.000 users.
=> Docs: clarify recipients for notifications endpoint

openapi/spec/openapi.json
Specify `type` of `NotificationPayload`, to make it a valid json-schema and recognized by the docs parser.
=> fix: define type for NotificationPayload

docs/redirects.json
Redirect https://magicbell.com/docs/rest-api/idempotent-requests to https://magicbell.com/docs/rest-api/overview#idempotent-requests
=> fix: redirect idempotent-requests to section on overview page

docs/redirects.json
Adds redirect to forward `https://www.magicbell.com/docs/rest-api/authentication` to `https://www.magicbell.com/docs/api-authentication`
=> chore: add redirect for api-authentication page

docs/src/components/layout/Content.tsx, docs/src/components/layout/Header.tsx, docs/src/components/menu/MobileMenu.tsx, docs/styles/globals.css
- H1 `font-size` doesn't look good on mobile.
- The MagicBell logo and hamburger icon on mobile nav wasn't visible.
- Some other minor nav bar improvements.
Before                                  |  After
:-------------------------:|:-------------------------:
> Description here
> Fix [#1]()
=> fix: make heading size dynamic, fix mobile nav

docs/src/components/CollapsedSection.tsx, docs/src/components/graphql/Field.tsx, docs/src/components/graphql/FieldArguments.tsx, docs/src/components/graphql/Headers.tsx, docs/src/components/graphql/InputArgument.tsx, docs/src/components/graphql/Type.tsx, docs/src/components/openapi/HeaderParameters.tsx, docs/src/components/openapi/Operation.tsx, docs/src/components/openapi/Parameter.tsx, docs/src/components/openapi/QueryParameters.tsx, docs/src/components/openapi/RequestBody.tsx, docs/src/components/openapi/SchemaObject.tsx, docs/styles/globals.css, docs/tailwind.config.js
Improved design of API tables according to DarkMagic theme: 
- Dimmed table borders
- Changed label text colors
- Fixed Padding
- Changed `Read more` button to follow DarkMagic
> Fix [#1]()
=> design: api reference styling

openapi/spec/openapi.json
Rename operation-id to list (paginated) instead of get (one)
=> chore: rename push-subscriptions-get to push-subscriptions-list

.github/actions/smoke-test/dist/index.js, openapi/scripts/smoke-test.ts
Fetch broadcast ids during warmup so operations like `broadcasts-get` have data to act upon.
=> feat: prefetch broadcast ids to use during smoke tests

openapi/spec/openapi.json
Title can be `null` when the delivery hasn't seen the template parser yet.
=> spec: allow null for delivery title

.github/actions/setup-node/action.yml, .github/workflows/changeset.yml, .github/workflows/docs.yaml, .github/workflows/openapi.yml
Change cache paths to be based on monorepo root, as we now have a single yarn.lock
=> fix: ensure cache is based on monorepo root

.changeset/forty-jeans-cough.md, openapi/spec/openapi.json
Remove the `total` and `total_pages` properties from the response of the following requests:
- `GET /broadcasts`.
- `GET /broadcasts/{broadcast-id}/notifications`.
- `GET /users`.
=> spec: remove `total` and `total_pages` props from paginated responses

.github/workflows/update-postman-collection.yml
This PR adds a workflow that will automatically update our Postman collections when new commits are added to the main branch. 
We have an [OpenAPI v3.0 specification json file](https://github.com/magicbell-io/public/blob/main/openapi/spec/openapi.json) in this repository.
1. The OpenAPI Spec is converted to a Postman Collection (v2) format with [OpenAPI to Postman CLI ](https://github.com/postmanlabs/openapi-to-postman#-command-line-interface)
2. The Postman Collection Format is JSON. The JSON object is added as a value to the `collection` property with [jq](https://github.com/stedolan/jq).
The [Postman API](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a?entity=request-12959542-bc8b292b-ffbb-4c67-a2a1-2fc416e2a …
=> feat: add workflow to automatically update postman collections

.changeset/lazy-kings-shave.md, openapi/spec/openapi.json
Remove the beta flags from the broadcasts apis. This includes:
- `GET /broadcasts`
- `GET /broadcasts/{broadcast_id}`
- `GET /broadcasts/{broadcast_id}/notifications`
=> spec: remove beta flag from broadcasts endpoints

.changeset/small-penguins-film.md, openapi/spec/openapi.json
Remove the beta flags from the users push-subscriptions apis. This includes:
- `GET /users/{user_id}/push_subscriptions`
- `DELETE /users/{user_id}/push_subscriptions/{subscription_id}`
=> spec: remove beta flag from users push-subscriptions endpoints

openapi/scripts/smoke-test.ts
Added a `--server-url` flag to the smoke test, and a `--help` to make testing easier
```
❯ tsx scripts/smoke-test.ts --help
Usage: 
tsx scripts/smoke-test.ts [--spec <path>] [--server <url>] [--op <operation>]'
Options:
--spec <path>     Path to OpenAPI spec file (default: 'spec/openapi.json')
--server <url>    URL of server to test (default: process.env.SERVER_URL)
--op <operation>  Test only the specified operation (default: test all operations)
Examples:
tsx scripts/smoke-test.ts --spec spec/openapi.json
tsx scripts/smoke-test.ts --op users-list
tsx scripts/smoke-test.ts --op users-list --server http://api-review-url.example.com
```
=> chore: accept custom server url

.github/actions/setup-node/action.yml, .github/actions/smoke-test/dist/index.js, docs/lib/openapi.ts, openapi/scripts/smoke-test.ts, openapi/scripts/validate-openapi.ts, openapi/spec/openapi.json
Adds summaries to resources. These summaries are part of the OpenAPI spec, and can then be used to decorate `magicbell --help`
Also adds a validation to the spec validator that check if all root paths, such as `/broadcasts` and `/notifications` have a summary defined.
=> feat: add resource summaries

.github/actions/smoke-test/dist/index.js, openapi/scripts/smoke-test.ts
Don't include a body when making OPTIONS requests. AWS lambdas don't like it, and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) says it shouldn't be there anyways.
=> chore: don't include body for options requests

.github/actions/smoke-test/dist/index.js, openapi/scripts/smoke-test.ts
This logs the CURL statement for failed smoke-tests, like:
```
Running smoke tests against https://api_magicbell_dev/
Broadcasts not ready yet, waiting 3 seconds before trying again.
⚠ POST /subscriptions (id: subscriptions-create)
✖ expected 1 to equal 2
✔ HTTP 401: request with invalid auth headers returns 401 unauthorized
✔ HTTP 200: request with valid api key and payload returns expected response
✔ HTTP 200: options request returns cors headers
---- Error Summary ----
✖ POST /subscriptions (id: subscriptions-create)
✖ HTTP 401: request without authentication headers return 401 unauthorized
error: expected 1 to equal 2
request: curl -X POST https://api.magicbell.dev/subscriptions -H 'content-type: application/json' -H 'accept: application/json' -H 'user-agent: …
```
=> chore: log curl request for failed smoke tests
