magicbell-io/public

- docs/README.md
- docs/pages/[...slug].tsx
Forgot to change when moving to monorepo :)
> Update links from `docs` to `public`

- .github/workflows/openapi.yml
Separate openapi `validate` and `smoke-test`  steps into jobs.
> ci: separate openapi validate & smoke-test steps into jobs

- openapi/scripts/smoke-test.ts
Throws an error unless all required env variables are set. 
> Fix [#1]()
> Throw an error unless all required env variables are set

- docs/vercel-ignore-step.sh
Fix #40 that was merged too early :)
Ref #36
> ci(vercel): fix ac4df74da497b2efd06fbfdeb667a40b15a55571

- docs/vercel-ignore-step.sh
Fixes https://github.com/magicbell-io/public/pull/41#discussion_r1047353451
> chore(vercel): more explicit log message for ignore step

- docs/docs/slack.mdx
> docs(slack): fixes grammar

- docs/redirects.json
Symlink the output directory in the docs sub-directory to root so vercel can detect and thus preview the deployment automatically for PRs
> Fix **[#14](https://github.com/magicbell-io/public/issues/14)**
> fix(preview-deployments): add /docs redirection

- docs/docs/slack/custom-apps.mdx
> Docs(Slack): Fix typos

- docs/docs/api-authentication.mdx
`docs/api-authentication.mdx`
```md
---
title: REST API Reference
subtitle: Explore the MagicBell REST API
---
```
`docs/api-authentication.mdx`
```md
---
title: Authentication 
subtitle: Learn how to use Authentication in your MagicBell Project
---
```
> Fix [#1]()
> fix(docs): correct authentication page metadata

- .github/actions/smoke-test/dist/index.js
- openapi/package.json
- openapi/scripts/smoke-test.ts
- package.json
The test for missing auth headers should verify a 401 unauthorized response. 
> Fix [#1]()
> Fixes the missing auth headers test

- docs/docs/index.mdx
> CTA links to Typeform instead of Calendly
> Fix [#1]()
> Link change to Demo CTA

- openapi/scripts/smoke-test.ts
The smoketests have an setup procedure that creates a bunch of notifications that can be worked with during tests. Think of; creating a notification during init, so we have a notificationId that we can use for our "mark as read" test.
As our job runner handles the create-notification requests in an async way, created notifications might not be ready when the tests runs. Resulting in the famous "_Ran out of notifications to act upon. Some have been created, but aren't ready yet. Please rerun this test in a sec_" message.
To make our smoke-tests more resilient, I've added a retry mechanism that waits for notifications during initialization. It does this by fetching the notifications (like before), and waiting with an exponential backoff before it retries fetching in case the notifications …
> feat: add retry with exponential backoff to smoke-test setup

- openapi/scripts/validate-openapi.ts
Add basic validation for path params:
- guard brace style, ensure that we use `{param}` and not `(param)`
- ensure that we have a same amount of closing braces, as there are opening braces
```
Path "/push_subscriptions/(device_token}" contains parentheses, please use curly braces for path params.
Path "/push_subscriptions/(device_token}" has mismatched braces, { and } must be balanced.
Path "/users/(user_id)/push_subscriptions" contains parentheses, please use curly braces for path params.
error Command failed with exit code 1.
```
> chore: add openapi path validation

- openapi/spec/openapi.json
Fix typo in operation-id, which causes it to be included in the wrong resource.
> chore: fix typo in operation id

- openapi/spec/openapi.json
Adds the /broadcast endpoint to the openapi spec.
> feat: add /broadcasts endpoint to openapi spec

- .github/actions/smoke-test/dist/index.js
- openapi/scripts/smoke-test.ts
- openapi/spec/openapi.json
Adds the `/broadcast/{broadcast_id}` endpoint to the openapi spec.
> feat: add /broadcasts/{broadcast_id} endpoint to openapi spec

- .github/actions/smoke-test/dist/index.js
- openapi/scripts/smoke-test.ts
- openapi/spec/openapi.json
Adds the `/broadcast/{broadcast_id}/notifications` endpoint to the openapi spec.
> feat: add /broadcasts/{broadcast_id}/notifications endpoint to openapi spec

- .github/actions/smoke-test/dist/index.js
- openapi/scripts/smoke-test.ts
> chore: improve error message when smoke-test fails (#88

- .changeset/nasty-deers-jog.md
- openapi/spec/openapi.json
rename operation from users-fetch to users-get to match convention.
> spec: fix operation-id

- docs/docs/index.mdx
- docs/docs/rest-api/overview.mdx
- docs/docs/web-push.mdx
- docs/docs/whats-next.mdx
- docs/redirects.json
- docs/sitemap.json
* Minor content edits 
* Navigation changes
> Fix [#1]()
> [Docs] Content Updates - May 25

- .github/workflows/update-postman-collection.yml
- openapi/spec/openapi.json
A postman review collection for easily testing API updates
> Fix [#1]()
> Postman review collection

- .changeset/mighty-dancers-pay.md
- openapi/spec/openapi.json
Adds specs for the `/users/{id}/notifications` endpoint
> spec: add `/users/{id}/notifications`

- openapi/spec/openapi.json
Adds specs for the metrics endpoints. This consists of three endpoints:
- `GET /metrics`
- `GET /metrics/categories`
- `GET /metrics/topics`
> spec: add metrics endpoints

- docs/docs/adding-magicbell-to-your-product.mdx
- docs/docs/email/amazon-ses.mdx
- docs/docs/index.mdx
- docs/redirects.json
* Fixes broken links
* Fixes incorrect doc articles
> Fix [#1]()
> Chore - Edits and corrections in Docs

- docs/docs/email/amazon-ses.mdx
Fixes the key name in the text and docs
> Fix [#1]()
> Chore - correct SES key in docs

- openapi/spec/openapi.json
Adds the user auth scoped `GET /subscriptions` to the openapi spec. 
> Fix [#1]()
> add entry for GET push subscription list (user-scoped)

- openapi/package.json
- openapi/scripts/validate-openapi.ts
- openapi/spec/openapi.json
- yarn.lock
- improve spec validator by also checking response schemas & examples, and showing nicer schema error messages
- Improve spec file by fixing schemas and adding examples.
> spec: fix response schemas & add missing examples

- docs/src/components/code/HighlightedCode.tsx
- docs/src/components/code/HighlightedCodeHeader.tsx
- docs/src/components/tabs/TabsHeader.tsx
- docs/tailwind.config.js
Fixes some colors in code snippets and borders
| before | after |
| --- | --- |
| ![image](https://github.com/magicbell-io/public/assets/1196524/c7c52e53-481a-4a61-87d6-349f33024449) | ![image](https://github.com/magicbell-io/public/assets/1196524/ff08b819-56b4-4428-9921-11c55c570534) |
> chore: fix colors of code snippets and borders

- openapi/spec/openapi.json
* Topic recipient for broadcasts
* Updated description for broadcasts and some help links
> Fix [#1]()
> Update OpenAPI spec to support Topic recipient for broadcasts 
